### ISSUE TITLE
docs: publishing

### ISSUE THREAD

**Issue by azu** [githon/githon#34]
We should creat "Publishing" page on docs.

Move https://githon.netlify.app/faq.html faq to separated page.

**Comment by azu** [comment]
GitHub Pages and Netlify is good hosting example.

**Comment by liliancavalet** [comment]
Hello, I would like to work in this issue, can you give me more information about it?

**Comment by azu** [comment]
Hi, We want to add "Publish" guide into our document.

Examples.

- [Deploying | VuePress](https://vuepress.vuejs.org/guide/deploy.html#google-firebase)
- [Publishing your site · Docusaurus](https://docusaurus.io/docs/en/publishing)

As a result, the user can know how to deploy own HonKit book to hosting site like GitHub pages.

**Comment by liliancavalet** [comment]
Ok, I think I can do it for GitHub pages. Can you assign me to this issue?

**Comment by atg-abhishek** [comment]
Is there a recommended way to deploy to GH Pages?

**Comment by azu** [comment]
GitHub Actions is easy and useful.

[GitHub Actions for GitHub Pages ](https://github.com/peaceiris/actions-gh-pages) helps you to deploy gh-pages.

```yaml
name: deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: npx honkit build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
```

**Comment by atg-abhishek** [comment]
Ah fantastic @azu - going to try this out now!

**Comment by atg-abhishek** [comment]
Ok it works quite well @azu, your quick response is much appreciated!! I'm writing [this book here](https://atg-abhishek.github.io/green-ai-handbook/) and will look to make a PR for the examples section of your repo in a few weeks once it is more fleshed out.

**Comment by nablidev** [comment]
@azu Thank you for your answer. It helped me. However, GitHub stopped supporting Ubuntu 18.04 on April 1, 2023. So:

```yml

runs-on: ubuntu-18.04

```

needs to be changed to 

```

runs-on: ubuntu-latest


```

Otherwise no `runner` is going to be able to pick the `job`

**Comment by azu** [comment]
Yes. It will probably look something like this

```
name: deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npx honkit build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
```

Welcome to PR.
